//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtleBugNET.BugNET {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://bugnetproject.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://bugnetproject.com/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://bugnetproject.com/")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private bool IsClosedStateField;
        
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        private int SortOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsClosedState {
            get {
                return this.IsClosedStateField;
            }
            set {
                if ((this.IsClosedStateField.Equals(value) != true)) {
                    this.IsClosedStateField = value;
                    this.RaisePropertyChanged("IsClosedState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://bugnetproject.com/")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private bool AllowIssueVotingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        private System.Guid ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorDisplayNameField;
        
        private bool DisabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UploadPathField;
        
        private TurtleBugNET.BugNET.ProjectAccessType AccessTypeField;
        
        private bool AllowAttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SvnRepositoryUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool AllowIssueVoting {
            get {
                return this.AllowIssueVotingField;
            }
            set {
                if ((this.AllowIssueVotingField.Equals(value) != true)) {
                    this.AllowIssueVotingField = value;
                    this.RaisePropertyChanged("AllowIssueVoting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Guid ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreatorUserName {
            get {
                return this.CreatorUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorUserNameField, value) != true)) {
                    this.CreatorUserNameField = value;
                    this.RaisePropertyChanged("CreatorUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CreatorDisplayName {
            get {
                return this.CreatorDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorDisplayNameField, value) != true)) {
                    this.CreatorDisplayNameField = value;
                    this.RaisePropertyChanged("CreatorDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Disabled {
            get {
                return this.DisabledField;
            }
            set {
                if ((this.DisabledField.Equals(value) != true)) {
                    this.DisabledField = value;
                    this.RaisePropertyChanged("Disabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ManagerUserName {
            get {
                return this.ManagerUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerUserNameField, value) != true)) {
                    this.ManagerUserNameField = value;
                    this.RaisePropertyChanged("ManagerUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ManagerDisplayName {
            get {
                return this.ManagerDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerDisplayNameField, value) != true)) {
                    this.ManagerDisplayNameField = value;
                    this.RaisePropertyChanged("ManagerDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string UploadPath {
            get {
                return this.UploadPathField;
            }
            set {
                if ((object.ReferenceEquals(this.UploadPathField, value) != true)) {
                    this.UploadPathField = value;
                    this.RaisePropertyChanged("UploadPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public TurtleBugNET.BugNET.ProjectAccessType AccessType {
            get {
                return this.AccessTypeField;
            }
            set {
                if ((this.AccessTypeField.Equals(value) != true)) {
                    this.AccessTypeField = value;
                    this.RaisePropertyChanged("AccessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool AllowAttachments {
            get {
                return this.AllowAttachmentsField;
            }
            set {
                if ((this.AllowAttachmentsField.Equals(value) != true)) {
                    this.AllowAttachmentsField = value;
                    this.RaisePropertyChanged("AllowAttachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SvnRepositoryUrl {
            get {
                return this.SvnRepositoryUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SvnRepositoryUrlField, value) != true)) {
                    this.SvnRepositoryUrlField = value;
                    this.RaisePropertyChanged("SvnRepositoryUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectAccessType", Namespace="http://bugnetproject.com/")]
    public enum ProjectAccessType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Public = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bugnetproject.com/", ConfigurationName="BugNET.BugNetServicesSoap")]
    public interface BugNetServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/ValidIssue", ReplyAction="*")]
        bool ValidIssue(int issueId);
        
        // CODEGEN: Generating message contract since element name repository from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/CreateNewIssueRevision", ReplyAction="*")]
        TurtleBugNET.BugNET.CreateNewIssueRevisionResponse CreateNewIssueRevision(TurtleBugNET.BugNET.CreateNewIssueRevisionRequest request);
        
        // CODEGEN: Generating message contract since element name creatorUserName from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/CreateNewIssueAttachment", ReplyAction="*")]
        TurtleBugNET.BugNET.CreateNewIssueAttachmentResponse CreateNewIssueAttachment(TurtleBugNET.BugNET.CreateNewIssueAttachmentRequest request);
        
        // CODEGEN: Generating message contract since element name categoryId from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/RenameCategory", ReplyAction="*")]
        TurtleBugNET.BugNET.RenameCategoryResponse RenameCategory(TurtleBugNET.BugNET.RenameCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name categoryId from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/MoveCategory", ReplyAction="*")]
        TurtleBugNET.BugNET.MoveCategoryResponse MoveCategory(TurtleBugNET.BugNET.MoveCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name projectId from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetCategories", ReplyAction="*")]
        TurtleBugNET.BugNET.GetCategoriesResponse GetCategories(TurtleBugNET.BugNET.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name projectId from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/AddCategory", ReplyAction="*")]
        TurtleBugNET.BugNET.AddCategoryResponse AddCategory(TurtleBugNET.BugNET.AddCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name categoryId from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/DeleteCategory", ReplyAction="*")]
        TurtleBugNET.BugNET.DeleteCategoryResponse DeleteCategory(TurtleBugNET.BugNET.DeleteCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetResolutionsResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetResolutions", ReplyAction="*")]
        TurtleBugNET.BugNET.GetResolutionsResponse GetResolutions(TurtleBugNET.BugNET.GetResolutionsRequest request);
        
        // CODEGEN: Generating message contract since element name GetMilestonesResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetMilestones", ReplyAction="*")]
        TurtleBugNET.BugNET.GetMilestonesResponse GetMilestones(TurtleBugNET.BugNET.GetMilestonesRequest request);
        
        // CODEGEN: Generating message contract since element name GetIssueTypesResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetIssueTypes", ReplyAction="*")]
        TurtleBugNET.BugNET.GetIssueTypesResponse GetIssueTypes(TurtleBugNET.BugNET.GetIssueTypesRequest request);
        
        // CODEGEN: Generating message contract since element name GetPrioritiesResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetPriorities", ReplyAction="*")]
        TurtleBugNET.BugNET.GetPrioritiesResponse GetPriorities(TurtleBugNET.BugNET.GetPrioritiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetStatusResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetStatus", ReplyAction="*")]
        TurtleBugNET.BugNET.GetStatusResponse GetStatus(TurtleBugNET.BugNET.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since element name ProjectCode from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetProjectId", ReplyAction="*")]
        TurtleBugNET.BugNET.GetProjectIdResponse GetProjectId(TurtleBugNET.BugNET.GetProjectIdRequest request);
        
        // CODEGEN: Generating message contract since element name Filter from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetProjectIssues", ReplyAction="*")]
        TurtleBugNET.BugNET.GetProjectIssuesResponse GetProjectIssues(TurtleBugNET.BugNET.GetProjectIssuesRequest request);
        
        // CODEGEN: Generating message contract since element name GetStatusObjectsResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetStatusObjects", ReplyAction="*")]
        TurtleBugNET.BugNET.GetStatusObjectsResponse GetStatusObjects(TurtleBugNET.BugNET.GetStatusObjectsRequest request);
        
        // CODEGEN: Generating message contract since element name GetProjectsResult from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/GetProjects", ReplyAction="*")]
        TurtleBugNET.BugNET.GetProjectsResponse GetProjects(TurtleBugNET.BugNET.GetProjectsRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://bugnetproject.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/LogIn", ReplyAction="*")]
        TurtleBugNET.BugNET.LogInResponse LogIn(TurtleBugNET.BugNET.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bugnetproject.com/LogOut", ReplyAction="*")]
        void LogOut();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewIssueRevisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewIssueRevision", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.CreateNewIssueRevisionRequestBody Body;
        
        public CreateNewIssueRevisionRequest() {
        }
        
        public CreateNewIssueRevisionRequest(TurtleBugNET.BugNET.CreateNewIssueRevisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class CreateNewIssueRevisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int issueId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string repository;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string revisionAuthor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string revisionDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revisionMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string changeset;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string branch;
        
        public CreateNewIssueRevisionRequestBody() {
        }
        
        public CreateNewIssueRevisionRequestBody(int revision, int issueId, string repository, string revisionAuthor, string revisionDate, string revisionMessage, string changeset, string branch) {
            this.revision = revision;
            this.issueId = issueId;
            this.repository = repository;
            this.revisionAuthor = revisionAuthor;
            this.revisionDate = revisionDate;
            this.revisionMessage = revisionMessage;
            this.changeset = changeset;
            this.branch = branch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewIssueRevisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewIssueRevisionResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.CreateNewIssueRevisionResponseBody Body;
        
        public CreateNewIssueRevisionResponse() {
        }
        
        public CreateNewIssueRevisionResponse(TurtleBugNET.BugNET.CreateNewIssueRevisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class CreateNewIssueRevisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateNewIssueRevisionResult;
        
        public CreateNewIssueRevisionResponseBody() {
        }
        
        public CreateNewIssueRevisionResponseBody(bool CreateNewIssueRevisionResult) {
            this.CreateNewIssueRevisionResult = CreateNewIssueRevisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewIssueAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewIssueAttachment", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.CreateNewIssueAttachmentRequestBody Body;
        
        public CreateNewIssueAttachmentRequest() {
        }
        
        public CreateNewIssueAttachmentRequest(TurtleBugNET.BugNET.CreateNewIssueAttachmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class CreateNewIssueAttachmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int issueId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string creatorUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] attachment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int size;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string description;
        
        public CreateNewIssueAttachmentRequestBody() {
        }
        
        public CreateNewIssueAttachmentRequestBody(int issueId, string creatorUserName, string fileName, string contentType, byte[] attachment, int size, string description) {
            this.issueId = issueId;
            this.creatorUserName = creatorUserName;
            this.fileName = fileName;
            this.contentType = contentType;
            this.attachment = attachment;
            this.size = size;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewIssueAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewIssueAttachmentResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.CreateNewIssueAttachmentResponseBody Body;
        
        public CreateNewIssueAttachmentResponse() {
        }
        
        public CreateNewIssueAttachmentResponse(TurtleBugNET.BugNET.CreateNewIssueAttachmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class CreateNewIssueAttachmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateNewIssueAttachmentResult;
        
        public CreateNewIssueAttachmentResponseBody() {
        }
        
        public CreateNewIssueAttachmentResponseBody(bool CreateNewIssueAttachmentResult) {
            this.CreateNewIssueAttachmentResult = CreateNewIssueAttachmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenameCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenameCategory", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.RenameCategoryRequestBody Body;
        
        public RenameCategoryRequest() {
        }
        
        public RenameCategoryRequest(TurtleBugNET.BugNET.RenameCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class RenameCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public RenameCategoryRequestBody() {
        }
        
        public RenameCategoryRequestBody(string categoryId, string name) {
            this.categoryId = categoryId;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenameCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenameCategoryResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.RenameCategoryResponseBody Body;
        
        public RenameCategoryResponse() {
        }
        
        public RenameCategoryResponse(TurtleBugNET.BugNET.RenameCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RenameCategoryResponseBody {
        
        public RenameCategoryResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveCategory", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.MoveCategoryRequestBody Body;
        
        public MoveCategoryRequest() {
        }
        
        public MoveCategoryRequest(TurtleBugNET.BugNET.MoveCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class MoveCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldParentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newParentId;
        
        public MoveCategoryRequestBody() {
        }
        
        public MoveCategoryRequestBody(string categoryId, string oldParentId, string newParentId) {
            this.categoryId = categoryId;
            this.oldParentId = oldParentId;
            this.newParentId = newParentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveCategoryResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.MoveCategoryResponseBody Body;
        
        public MoveCategoryResponse() {
        }
        
        public MoveCategoryResponse(TurtleBugNET.BugNET.MoveCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MoveCategoryResponseBody {
        
        public MoveCategoryResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest() {
        }
        
        public GetCategoriesRequest(TurtleBugNET.BugNET.GetCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetCategoriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectId;
        
        public GetCategoriesRequestBody() {
        }
        
        public GetCategoriesRequestBody(string projectId) {
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse() {
        }
        
        public GetCategoriesResponse(TurtleBugNET.BugNET.GetCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCategoriesResult;
        
        public GetCategoriesResponseBody() {
        }
        
        public GetCategoriesResponseBody(string GetCategoriesResult) {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategory", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.AddCategoryRequestBody Body;
        
        public AddCategoryRequest() {
        }
        
        public AddCategoryRequest(TurtleBugNET.BugNET.AddCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class AddCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string parentCategoryId;
        
        public AddCategoryRequestBody() {
        }
        
        public AddCategoryRequestBody(string projectId, string name, string parentCategoryId) {
            this.projectId = projectId;
            this.name = name;
            this.parentCategoryId = parentCategoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategoryResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.AddCategoryResponseBody Body;
        
        public AddCategoryResponse() {
        }
        
        public AddCategoryResponse(TurtleBugNET.BugNET.AddCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class AddCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddCategoryResult;
        
        public AddCategoryResponseBody() {
        }
        
        public AddCategoryResponseBody(int AddCategoryResult) {
            this.AddCategoryResult = AddCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCategory", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.DeleteCategoryRequestBody Body;
        
        public DeleteCategoryRequest() {
        }
        
        public DeleteCategoryRequest(TurtleBugNET.BugNET.DeleteCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class DeleteCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoryId;
        
        public DeleteCategoryRequestBody() {
        }
        
        public DeleteCategoryRequestBody(string categoryId) {
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCategoryResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.DeleteCategoryResponseBody Body;
        
        public DeleteCategoryResponse() {
        }
        
        public DeleteCategoryResponse(TurtleBugNET.BugNET.DeleteCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteCategoryResponseBody {
        
        public DeleteCategoryResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResolutionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResolutions", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetResolutionsRequestBody Body;
        
        public GetResolutionsRequest() {
        }
        
        public GetResolutionsRequest(TurtleBugNET.BugNET.GetResolutionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetResolutionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        public GetResolutionsRequestBody() {
        }
        
        public GetResolutionsRequestBody(int ProjectId) {
            this.ProjectId = ProjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResolutionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResolutionsResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetResolutionsResponseBody Body;
        
        public GetResolutionsResponse() {
        }
        
        public GetResolutionsResponse(TurtleBugNET.BugNET.GetResolutionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetResolutionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurtleBugNET.BugNET.ArrayOfString GetResolutionsResult;
        
        public GetResolutionsResponseBody() {
        }
        
        public GetResolutionsResponseBody(TurtleBugNET.BugNET.ArrayOfString GetResolutionsResult) {
            this.GetResolutionsResult = GetResolutionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMilestonesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMilestones", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetMilestonesRequestBody Body;
        
        public GetMilestonesRequest() {
        }
        
        public GetMilestonesRequest(TurtleBugNET.BugNET.GetMilestonesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetMilestonesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        public GetMilestonesRequestBody() {
        }
        
        public GetMilestonesRequestBody(int ProjectId) {
            this.ProjectId = ProjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMilestonesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMilestonesResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetMilestonesResponseBody Body;
        
        public GetMilestonesResponse() {
        }
        
        public GetMilestonesResponse(TurtleBugNET.BugNET.GetMilestonesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetMilestonesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurtleBugNET.BugNET.ArrayOfString GetMilestonesResult;
        
        public GetMilestonesResponseBody() {
        }
        
        public GetMilestonesResponseBody(TurtleBugNET.BugNET.ArrayOfString GetMilestonesResult) {
            this.GetMilestonesResult = GetMilestonesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIssueTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIssueTypes", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetIssueTypesRequestBody Body;
        
        public GetIssueTypesRequest() {
        }
        
        public GetIssueTypesRequest(TurtleBugNET.BugNET.GetIssueTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetIssueTypesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        public GetIssueTypesRequestBody() {
        }
        
        public GetIssueTypesRequestBody(int ProjectId) {
            this.ProjectId = ProjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIssueTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIssueTypesResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetIssueTypesResponseBody Body;
        
        public GetIssueTypesResponse() {
        }
        
        public GetIssueTypesResponse(TurtleBugNET.BugNET.GetIssueTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetIssueTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurtleBugNET.BugNET.ArrayOfString GetIssueTypesResult;
        
        public GetIssueTypesResponseBody() {
        }
        
        public GetIssueTypesResponseBody(TurtleBugNET.BugNET.ArrayOfString GetIssueTypesResult) {
            this.GetIssueTypesResult = GetIssueTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrioritiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorities", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetPrioritiesRequestBody Body;
        
        public GetPrioritiesRequest() {
        }
        
        public GetPrioritiesRequest(TurtleBugNET.BugNET.GetPrioritiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetPrioritiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        public GetPrioritiesRequestBody() {
        }
        
        public GetPrioritiesRequestBody(int ProjectId) {
            this.ProjectId = ProjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrioritiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrioritiesResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetPrioritiesResponseBody Body;
        
        public GetPrioritiesResponse() {
        }
        
        public GetPrioritiesResponse(TurtleBugNET.BugNET.GetPrioritiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetPrioritiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurtleBugNET.BugNET.ArrayOfString GetPrioritiesResult;
        
        public GetPrioritiesResponseBody() {
        }
        
        public GetPrioritiesResponseBody(TurtleBugNET.BugNET.ArrayOfString GetPrioritiesResult) {
            this.GetPrioritiesResult = GetPrioritiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(TurtleBugNET.BugNET.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(int ProjectId) {
            this.ProjectId = ProjectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(TurtleBugNET.BugNET.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurtleBugNET.BugNET.ArrayOfString GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(TurtleBugNET.BugNET.ArrayOfString GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectId", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetProjectIdRequestBody Body;
        
        public GetProjectIdRequest() {
        }
        
        public GetProjectIdRequest(TurtleBugNET.BugNET.GetProjectIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetProjectIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProjectCode;
        
        public GetProjectIdRequestBody() {
        }
        
        public GetProjectIdRequestBody(string ProjectCode) {
            this.ProjectCode = ProjectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectIdResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetProjectIdResponseBody Body;
        
        public GetProjectIdResponse() {
        }
        
        public GetProjectIdResponse(TurtleBugNET.BugNET.GetProjectIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetProjectIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetProjectIdResult;
        
        public GetProjectIdResponseBody() {
        }
        
        public GetProjectIdResponseBody(int GetProjectIdResult) {
            this.GetProjectIdResult = GetProjectIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectIssuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectIssues", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetProjectIssuesRequestBody Body;
        
        public GetProjectIssuesRequest() {
        }
        
        public GetProjectIssuesRequest(TurtleBugNET.BugNET.GetProjectIssuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetProjectIssuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Filter;
        
        public GetProjectIssuesRequestBody() {
        }
        
        public GetProjectIssuesRequestBody(int ProjectId, string Filter) {
            this.ProjectId = ProjectId;
            this.Filter = Filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectIssuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectIssuesResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetProjectIssuesResponseBody Body;
        
        public GetProjectIssuesResponse() {
        }
        
        public GetProjectIssuesResponse(TurtleBugNET.BugNET.GetProjectIssuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetProjectIssuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurtleBugNET.BugNET.ArrayOfAnyType GetProjectIssuesResult;
        
        public GetProjectIssuesResponseBody() {
        }
        
        public GetProjectIssuesResponseBody(TurtleBugNET.BugNET.ArrayOfAnyType GetProjectIssuesResult) {
            this.GetProjectIssuesResult = GetProjectIssuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusObjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusObjects", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetStatusObjectsRequestBody Body;
        
        public GetStatusObjectsRequest() {
        }
        
        public GetStatusObjectsRequest(TurtleBugNET.BugNET.GetStatusObjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetStatusObjectsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int projectId;
        
        public GetStatusObjectsRequestBody() {
        }
        
        public GetStatusObjectsRequestBody(int projectId) {
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusObjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusObjectsResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetStatusObjectsResponseBody Body;
        
        public GetStatusObjectsResponse() {
        }
        
        public GetStatusObjectsResponse(TurtleBugNET.BugNET.GetStatusObjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetStatusObjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<TurtleBugNET.BugNET.Status> GetStatusObjectsResult;
        
        public GetStatusObjectsResponseBody() {
        }
        
        public GetStatusObjectsResponseBody(System.Collections.Generic.List<TurtleBugNET.BugNET.Status> GetStatusObjectsResult) {
            this.GetStatusObjectsResult = GetStatusObjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjects", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetProjectsRequestBody Body;
        
        public GetProjectsRequest() {
        }
        
        public GetProjectsRequest(TurtleBugNET.BugNET.GetProjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProjectsRequestBody {
        
        public GetProjectsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectsResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.GetProjectsResponseBody Body;
        
        public GetProjectsResponse() {
        }
        
        public GetProjectsResponse(TurtleBugNET.BugNET.GetProjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class GetProjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<TurtleBugNET.BugNET.Project> GetProjectsResult;
        
        public GetProjectsResponseBody() {
        }
        
        public GetProjectsResponseBody(System.Collections.Generic.List<TurtleBugNET.BugNET.Project> GetProjectsResult) {
            this.GetProjectsResult = GetProjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(TurtleBugNET.BugNET.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://bugnetproject.com/", Order=0)]
        public TurtleBugNET.BugNET.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(TurtleBugNET.BugNET.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bugnetproject.com/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(bool LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BugNetServicesSoapChannel : TurtleBugNET.BugNET.BugNetServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BugNetServicesSoapClient : System.ServiceModel.ClientBase<TurtleBugNET.BugNET.BugNetServicesSoap>, TurtleBugNET.BugNET.BugNetServicesSoap {
        
        public BugNetServicesSoapClient() {
        }
        
        public BugNetServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BugNetServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BugNetServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BugNetServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidIssue(int issueId) {
            return base.Channel.ValidIssue(issueId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.CreateNewIssueRevisionResponse TurtleBugNET.BugNET.BugNetServicesSoap.CreateNewIssueRevision(TurtleBugNET.BugNET.CreateNewIssueRevisionRequest request) {
            return base.Channel.CreateNewIssueRevision(request);
        }
        
        public bool CreateNewIssueRevision(int revision, int issueId, string repository, string revisionAuthor, string revisionDate, string revisionMessage, string changeset, string branch) {
            TurtleBugNET.BugNET.CreateNewIssueRevisionRequest inValue = new TurtleBugNET.BugNET.CreateNewIssueRevisionRequest();
            inValue.Body = new TurtleBugNET.BugNET.CreateNewIssueRevisionRequestBody();
            inValue.Body.revision = revision;
            inValue.Body.issueId = issueId;
            inValue.Body.repository = repository;
            inValue.Body.revisionAuthor = revisionAuthor;
            inValue.Body.revisionDate = revisionDate;
            inValue.Body.revisionMessage = revisionMessage;
            inValue.Body.changeset = changeset;
            inValue.Body.branch = branch;
            TurtleBugNET.BugNET.CreateNewIssueRevisionResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).CreateNewIssueRevision(inValue);
            return retVal.Body.CreateNewIssueRevisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.CreateNewIssueAttachmentResponse TurtleBugNET.BugNET.BugNetServicesSoap.CreateNewIssueAttachment(TurtleBugNET.BugNET.CreateNewIssueAttachmentRequest request) {
            return base.Channel.CreateNewIssueAttachment(request);
        }
        
        public bool CreateNewIssueAttachment(int issueId, string creatorUserName, string fileName, string contentType, byte[] attachment, int size, string description) {
            TurtleBugNET.BugNET.CreateNewIssueAttachmentRequest inValue = new TurtleBugNET.BugNET.CreateNewIssueAttachmentRequest();
            inValue.Body = new TurtleBugNET.BugNET.CreateNewIssueAttachmentRequestBody();
            inValue.Body.issueId = issueId;
            inValue.Body.creatorUserName = creatorUserName;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.attachment = attachment;
            inValue.Body.size = size;
            inValue.Body.description = description;
            TurtleBugNET.BugNET.CreateNewIssueAttachmentResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).CreateNewIssueAttachment(inValue);
            return retVal.Body.CreateNewIssueAttachmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.RenameCategoryResponse TurtleBugNET.BugNET.BugNetServicesSoap.RenameCategory(TurtleBugNET.BugNET.RenameCategoryRequest request) {
            return base.Channel.RenameCategory(request);
        }
        
        public void RenameCategory(string categoryId, string name) {
            TurtleBugNET.BugNET.RenameCategoryRequest inValue = new TurtleBugNET.BugNET.RenameCategoryRequest();
            inValue.Body = new TurtleBugNET.BugNET.RenameCategoryRequestBody();
            inValue.Body.categoryId = categoryId;
            inValue.Body.name = name;
            TurtleBugNET.BugNET.RenameCategoryResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).RenameCategory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.MoveCategoryResponse TurtleBugNET.BugNET.BugNetServicesSoap.MoveCategory(TurtleBugNET.BugNET.MoveCategoryRequest request) {
            return base.Channel.MoveCategory(request);
        }
        
        public void MoveCategory(string categoryId, string oldParentId, string newParentId) {
            TurtleBugNET.BugNET.MoveCategoryRequest inValue = new TurtleBugNET.BugNET.MoveCategoryRequest();
            inValue.Body = new TurtleBugNET.BugNET.MoveCategoryRequestBody();
            inValue.Body.categoryId = categoryId;
            inValue.Body.oldParentId = oldParentId;
            inValue.Body.newParentId = newParentId;
            TurtleBugNET.BugNET.MoveCategoryResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).MoveCategory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetCategoriesResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetCategories(TurtleBugNET.BugNET.GetCategoriesRequest request) {
            return base.Channel.GetCategories(request);
        }
        
        public string GetCategories(string projectId) {
            TurtleBugNET.BugNET.GetCategoriesRequest inValue = new TurtleBugNET.BugNET.GetCategoriesRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetCategoriesRequestBody();
            inValue.Body.projectId = projectId;
            TurtleBugNET.BugNET.GetCategoriesResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.AddCategoryResponse TurtleBugNET.BugNET.BugNetServicesSoap.AddCategory(TurtleBugNET.BugNET.AddCategoryRequest request) {
            return base.Channel.AddCategory(request);
        }
        
        public int AddCategory(string projectId, string name, string parentCategoryId) {
            TurtleBugNET.BugNET.AddCategoryRequest inValue = new TurtleBugNET.BugNET.AddCategoryRequest();
            inValue.Body = new TurtleBugNET.BugNET.AddCategoryRequestBody();
            inValue.Body.projectId = projectId;
            inValue.Body.name = name;
            inValue.Body.parentCategoryId = parentCategoryId;
            TurtleBugNET.BugNET.AddCategoryResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).AddCategory(inValue);
            return retVal.Body.AddCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.DeleteCategoryResponse TurtleBugNET.BugNET.BugNetServicesSoap.DeleteCategory(TurtleBugNET.BugNET.DeleteCategoryRequest request) {
            return base.Channel.DeleteCategory(request);
        }
        
        public void DeleteCategory(string categoryId) {
            TurtleBugNET.BugNET.DeleteCategoryRequest inValue = new TurtleBugNET.BugNET.DeleteCategoryRequest();
            inValue.Body = new TurtleBugNET.BugNET.DeleteCategoryRequestBody();
            inValue.Body.categoryId = categoryId;
            TurtleBugNET.BugNET.DeleteCategoryResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).DeleteCategory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetResolutionsResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetResolutions(TurtleBugNET.BugNET.GetResolutionsRequest request) {
            return base.Channel.GetResolutions(request);
        }
        
        public TurtleBugNET.BugNET.ArrayOfString GetResolutions(int ProjectId) {
            TurtleBugNET.BugNET.GetResolutionsRequest inValue = new TurtleBugNET.BugNET.GetResolutionsRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetResolutionsRequestBody();
            inValue.Body.ProjectId = ProjectId;
            TurtleBugNET.BugNET.GetResolutionsResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetResolutions(inValue);
            return retVal.Body.GetResolutionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetMilestonesResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetMilestones(TurtleBugNET.BugNET.GetMilestonesRequest request) {
            return base.Channel.GetMilestones(request);
        }
        
        public TurtleBugNET.BugNET.ArrayOfString GetMilestones(int ProjectId) {
            TurtleBugNET.BugNET.GetMilestonesRequest inValue = new TurtleBugNET.BugNET.GetMilestonesRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetMilestonesRequestBody();
            inValue.Body.ProjectId = ProjectId;
            TurtleBugNET.BugNET.GetMilestonesResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetMilestones(inValue);
            return retVal.Body.GetMilestonesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetIssueTypesResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetIssueTypes(TurtleBugNET.BugNET.GetIssueTypesRequest request) {
            return base.Channel.GetIssueTypes(request);
        }
        
        public TurtleBugNET.BugNET.ArrayOfString GetIssueTypes(int ProjectId) {
            TurtleBugNET.BugNET.GetIssueTypesRequest inValue = new TurtleBugNET.BugNET.GetIssueTypesRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetIssueTypesRequestBody();
            inValue.Body.ProjectId = ProjectId;
            TurtleBugNET.BugNET.GetIssueTypesResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetIssueTypes(inValue);
            return retVal.Body.GetIssueTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetPrioritiesResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetPriorities(TurtleBugNET.BugNET.GetPrioritiesRequest request) {
            return base.Channel.GetPriorities(request);
        }
        
        public TurtleBugNET.BugNET.ArrayOfString GetPriorities(int ProjectId) {
            TurtleBugNET.BugNET.GetPrioritiesRequest inValue = new TurtleBugNET.BugNET.GetPrioritiesRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetPrioritiesRequestBody();
            inValue.Body.ProjectId = ProjectId;
            TurtleBugNET.BugNET.GetPrioritiesResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetPriorities(inValue);
            return retVal.Body.GetPrioritiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetStatusResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetStatus(TurtleBugNET.BugNET.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public TurtleBugNET.BugNET.ArrayOfString GetStatus(int ProjectId) {
            TurtleBugNET.BugNET.GetStatusRequest inValue = new TurtleBugNET.BugNET.GetStatusRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetStatusRequestBody();
            inValue.Body.ProjectId = ProjectId;
            TurtleBugNET.BugNET.GetStatusResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetProjectIdResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetProjectId(TurtleBugNET.BugNET.GetProjectIdRequest request) {
            return base.Channel.GetProjectId(request);
        }
        
        public int GetProjectId(string ProjectCode) {
            TurtleBugNET.BugNET.GetProjectIdRequest inValue = new TurtleBugNET.BugNET.GetProjectIdRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetProjectIdRequestBody();
            inValue.Body.ProjectCode = ProjectCode;
            TurtleBugNET.BugNET.GetProjectIdResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetProjectId(inValue);
            return retVal.Body.GetProjectIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetProjectIssuesResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetProjectIssues(TurtleBugNET.BugNET.GetProjectIssuesRequest request) {
            return base.Channel.GetProjectIssues(request);
        }
        
        public TurtleBugNET.BugNET.ArrayOfAnyType GetProjectIssues(int ProjectId, string Filter) {
            TurtleBugNET.BugNET.GetProjectIssuesRequest inValue = new TurtleBugNET.BugNET.GetProjectIssuesRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetProjectIssuesRequestBody();
            inValue.Body.ProjectId = ProjectId;
            inValue.Body.Filter = Filter;
            TurtleBugNET.BugNET.GetProjectIssuesResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetProjectIssues(inValue);
            return retVal.Body.GetProjectIssuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetStatusObjectsResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetStatusObjects(TurtleBugNET.BugNET.GetStatusObjectsRequest request) {
            return base.Channel.GetStatusObjects(request);
        }
        
        public System.Collections.Generic.List<TurtleBugNET.BugNET.Status> GetStatusObjects(int projectId) {
            TurtleBugNET.BugNET.GetStatusObjectsRequest inValue = new TurtleBugNET.BugNET.GetStatusObjectsRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetStatusObjectsRequestBody();
            inValue.Body.projectId = projectId;
            TurtleBugNET.BugNET.GetStatusObjectsResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetStatusObjects(inValue);
            return retVal.Body.GetStatusObjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.GetProjectsResponse TurtleBugNET.BugNET.BugNetServicesSoap.GetProjects(TurtleBugNET.BugNET.GetProjectsRequest request) {
            return base.Channel.GetProjects(request);
        }
        
        public System.Collections.Generic.List<TurtleBugNET.BugNET.Project> GetProjects() {
            TurtleBugNET.BugNET.GetProjectsRequest inValue = new TurtleBugNET.BugNET.GetProjectsRequest();
            inValue.Body = new TurtleBugNET.BugNET.GetProjectsRequestBody();
            TurtleBugNET.BugNET.GetProjectsResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).GetProjects(inValue);
            return retVal.Body.GetProjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurtleBugNET.BugNET.LogInResponse TurtleBugNET.BugNET.BugNetServicesSoap.LogIn(TurtleBugNET.BugNET.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public bool LogIn(string userName, string password) {
            TurtleBugNET.BugNET.LogInRequest inValue = new TurtleBugNET.BugNET.LogInRequest();
            inValue.Body = new TurtleBugNET.BugNET.LogInRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            TurtleBugNET.BugNET.LogInResponse retVal = ((TurtleBugNET.BugNET.BugNetServicesSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        public void LogOut() {
            base.Channel.LogOut();
        }
    }
}
